-- =============================================================================
-- Flyway Database Migration: V1__init_schema.sql
-- Description: Initialize core RFID Tracking & Attendance Schema
-- Compatibility: PostgreSQL and H2
-- =============================================================================

-- 1. People Table
CREATE TABLE IF NOT EXISTS people (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    member_type VARCHAR(50) NOT NULL,
    external_ref VARCHAR(100) UNIQUE,
    group_label VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Staff Users (Administrators, Managers, Operators)
CREATE TABLE IF NOT EXISTS staff_users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    added_by_id BIGINT,
    password_change_required BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_staff_users_added_by FOREIGN KEY (added_by_id) REFERENCES staff_users(user_id) ON DELETE SET NULL
);

-- 3. RFID Cards
CREATE TABLE IF NOT EXISTS rfid_cards (
    card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. Card Mappings (Assigning RFID cards to Persons)
CREATE TABLE IF NOT EXISTS card_mappings (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP,
    CONSTRAINT fk_card_mappings_card FOREIGN KEY (card_id) REFERENCES rfid_cards(card_id) ON DELETE CASCADE,
    CONSTRAINT fk_card_mappings_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE CASCADE
);

-- 5. Attendance Sessions (Daily Work Sessions per Person)
CREATE TABLE IF NOT EXISTS attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    check_in_at TIMESTAMP NOT NULL,
    check_out_at TIMESTAMP,
    duration_minutes INTEGER,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    is_late BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_attendance_sessions_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE CASCADE
);

-- 6. Attendance Events (Raw RFID Tap Logs)
CREATE TABLE IF NOT EXISTS attendance_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid VARCHAR(100) NOT NULL,
    person_id BIGINT,
    decision VARCHAR(50) NOT NULL,
    event_type VARCHAR(50),
    reason VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(50) NOT NULL DEFAULT 'SIMULATED',
    CONSTRAINT fk_attendance_events_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE SET NULL
);

-- 7. System Configurations (Key-Value pairs)
CREATE TABLE IF NOT EXISTS system_configurations (
    config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value VARCHAR(500) NOT NULL
);

-- 8. Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(500),
    type VARCHAR(50),
    target_roles VARCHAR(100),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 9. Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    actor_role VARCHAR(50),
    action_type VARCHAR(100) NOT NULL,
    target_entity VARCHAR(100) NOT NULL,
    target_id VARCHAR(100),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(100)
);

-- Indexes for Query Performance
CREATE INDEX IF NOT EXISTS idx_people_group ON people(group_label);
CREATE INDEX IF NOT EXISTS idx_people_status ON people(status);
CREATE INDEX IF NOT EXISTS idx_people_member_type ON people(member_type);

CREATE INDEX IF NOT EXISTS idx_card_mappings_person_status ON card_mappings(person_id, status);
CREATE INDEX IF NOT EXISTS idx_card_mappings_card_status ON card_mappings(card_id, status);

CREATE INDEX IF NOT EXISTS idx_sessions_work_date ON attendance_sessions(work_date);
CREATE INDEX IF NOT EXISTS idx_sessions_person_date ON attendance_sessions(person_id, work_date);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON attendance_sessions(status);

CREATE INDEX IF NOT EXISTS idx_events_occurred_at ON attendance_events(occurred_at);
CREATE INDEX IF NOT EXISTS idx_events_person_id ON attendance_events(person_id);
CREATE INDEX IF NOT EXISTS idx_events_decision ON attendance_events(decision);
