-- =============================================================================
-- Flyway Database Migration: V2__fix_people_status_constraint.sql
-- Description: Drop legacy check constraint on people.status generated by
--              Hibernate to allow 'COMPLETED' status in PostgreSQL & H2
-- Compatibility: PostgreSQL and H2
-- =============================================================================

ALTER TABLE people DROP CONSTRAINT IF EXISTS people_status_check;
ALTER TABLE people DROP CONSTRAINT IF EXISTS check_status;

ALTER TABLE people ADD CONSTRAINT people_status_check 
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED'));
