-- V2__create_people.sql: Registered personnel (Employees & Students)
CREATE TABLE IF NOT EXISTS people (
    person_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    member_type VARCHAR(50) NOT NULL,
    external_ref VARCHAR(100) UNIQUE,
    group_label VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    joining_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_people_group ON people(group_label);
CREATE INDEX IF NOT EXISTS idx_people_status ON people(status);
CREATE INDEX IF NOT EXISTS idx_people_member_type ON people(member_type);
CREATE INDEX IF NOT EXISTS idx_people_joining_date ON people(joining_date);
