-- V3__create_rfid_cards.sql: Physical RFID cards & Personnel Mappings
CREATE TABLE IF NOT EXISTS rfid_cards (
    card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_mappings (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP,
    CONSTRAINT fk_card_mappings_card FOREIGN KEY (card_id) REFERENCES rfid_cards(card_id) ON DELETE CASCADE,
    CONSTRAINT fk_card_mappings_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rfid_cards_uid ON rfid_cards(card_uid);
CREATE INDEX IF NOT EXISTS idx_rfid_cards_status ON rfid_cards(status);
CREATE INDEX IF NOT EXISTS idx_card_mappings_person_status ON card_mappings(person_id, status);
CREATE INDEX IF NOT EXISTS idx_card_mappings_card_status ON card_mappings(card_id, status);
