-- V4__create_attendance.sql: Daily work sessions & Raw tap event logs
CREATE TABLE IF NOT EXISTS attendance_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    check_in_at TIMESTAMP NOT NULL,
    check_out_at TIMESTAMP,
    duration_minutes INTEGER,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    is_late BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_attendance_sessions_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attendance_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_uid VARCHAR(100) NOT NULL,
    person_id BIGINT,
    decision VARCHAR(50) NOT NULL,
    event_type VARCHAR(50),
    reason VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(50) NOT NULL DEFAULT 'SIMULATED',
    CONSTRAINT fk_attendance_events_person FOREIGN KEY (person_id) REFERENCES people(person_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_work_date ON attendance_sessions(work_date);
CREATE INDEX IF NOT EXISTS idx_sessions_person_date ON attendance_sessions(person_id, work_date);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON attendance_sessions(status);
CREATE INDEX IF NOT EXISTS idx_events_occurred_at ON attendance_events(occurred_at);
CREATE INDEX IF NOT EXISTS idx_events_person_id ON attendance_events(person_id);
CREATE INDEX IF NOT EXISTS idx_events_decision ON attendance_events(decision);
