-- V5__create_devices.sql: Hardware RFID scanner readers & Gate devices
CREATE TABLE IF NOT EXISTS rfid_devices (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_name VARCHAR(150) NOT NULL,
    device_key VARCHAR(100) NOT NULL UNIQUE,
    location VARCHAR(200) NOT NULL DEFAULT 'Main Gate',
    device_type VARCHAR(50) NOT NULL DEFAULT 'ESP32_RC522',
    status VARCHAR(50) NOT NULL DEFAULT 'ONLINE',
    last_heartbeat TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_devices_key ON rfid_devices(device_key);
CREATE INDEX IF NOT EXISTS idx_devices_status ON rfid_devices(status);
